### ISSUE TITLE
Reduce new allocations!

### ISSUE THREAD

**Issue by PDeveloper** [tbrosman/hxmath#23]
I notice that many function return a new structure. This in my opinion is unnecessary, since providing the clone() function allows a fast copy + modify, or in other cases then just modify in place. This should improve performance considerably in tight places.

I want to wait for your comment before proceeding in fixing some of these places. (I noticed Matrix3x3.multiplyScalar() function first)

**Comment by tbrosman** [comment]
Thought on this for a while. The new convention I'm going to use is:

* Operators will allocate new objects for clarity
* Properties will normally allocate new objects (e.g. Vector2.normal)
* All other functions will favor in-place versions where possible/practical

This will boost performance while keeping the interface clean.

**Comment by tbrosman** [comment]
The above convention has been applied to all Vector classes.

**Comment by player-03** [comment]
Haxe 4 has massively improved on this. Now whenever it can tell that an object allocation is redundant, it avoids the allocation. For instance, this code that would produce five allocations in Haxe 3 produces _zero_ in Haxe 4:

```haxe
trace((new Vector2(1, 2) + new Vector2(3, 4)) * new Vector2(5, 6));
```

[I made a demo so you can see for yourself.](https://try.haxe.org/#a967253C) The demo also goes into some detail on requirements and limitations.
