### ISSUE TITLE
Vector2 api missing functions

### ISSUE THREAD

**Issue by Krzycho666** [tbrosman/hxmath#29]
I've been using Vector2 class for a while now, and I miss some functionality out there. Could you please add some like:
- adding/substracting/multiplying/dividing number and Vector
- rotating Vector by angle
- Vector normalization to value
- Vector clamping/trimming

I would love to see them in official release.

**Comment by tbrosman** [comment]
The scalar multiplication function exists, I can add the scalar division pretty easily. Not sure how you would subtract/add a number with a vector though.

I can throw in rotate if it'll make life easier. I know it's pretty common in math libs to add it to the Vector class these days.

Regular normalization is in, but I assume you mean changing the length after as well? I could throw in some kind of normalizeTo function.

Clamp/trim has been on my mental todo list for a while :)

**Comment by Krzycho666** [comment]
Nice to see your agreement ;) Vector addition/substaction should be done similar do mult/div - just add/sub scal to x and y.
NormalizationTo  would be great, same as clamping/trimming.
It all can be done manualy with matrices, but it'd be easer.

**Comment by tbrosman** [comment]
Ah, yeah I'm not sure adding scalars directly to vectors would be a clean interface. They're not really compatibly objects. As for the normalization, default parameters are ridiculously slow, so I'm just going to have normalize and normalizeTo.

**Comment by tbrosman** [comment]
Here you go:

http://lib.haxe.org/p/hxmath

Version 0.10.0

**Comment by Krzycho666** [comment]
thank you ;) works as it should =]
