### ISSUE TITLE
errors running cpp tests

### ISSUE THREAD

**Issue by mboussaa** [tbrosman/hxmath#48]
running tests in hxmath with cpp does not work.
If you go to hxmath directory and try to run haxe test_cpp.hxml you will find too many errors
any solution ?

**Comment by tbrosman** [comment]
I am able to compile on windows and the CI jobs are running without issue: https://travis-ci.org/tbrosman/hxmath

What compiler are you using, which version of Haxe, and which version of hxcpp?

**Comment by mboussaa** [comment]
Haxe 3.3.0 / NekoVM 2.0.0 / haxelib 3.3.0 / last hxcpp version on github

**Comment by mboussaa** [comment]
in fact I resolved the issue. I had to install last haxecpp version from git

**Comment by tbrosman** [comment]
Ah, I haven't tried with higher than Haxe 3.2.0. FYI I'm using hxcpp 3.2.193.

**Comment by tbrosman** [comment]
Closing this since you resolved it.
