### ISSUE TITLE
errors running Neko

### ISSUE THREAD

**Issue by mboussaa** [tbrosman/hxmath#49]
root@mboussaa:/hxmath# neko bin/neko/Test.n 
Uncaught exception - load.c(398) : Invalid module : bin/neko/Test.n
any solution?
thanks

**Comment by tbrosman** [comment]
Did you build the neko project? From the root directory: `haxe .\test_neko.hxml`

**Comment by mboussaa** [comment]
yes in fact I could generate code for JS/PHP/JAVA/PYTHON/CPP/FLASH but with neko I am getting that error

**Comment by tbrosman** [comment]
Hmm... what version neko? I'm using 2.0.0 on my dev box (Windows) and the CI builds are using the latest from https://github.com/HaxeFoundation/neko.git.

**Comment by mboussaa** [comment]
The same I am using NekoVM 2.0.0

**Comment by tbrosman** [comment]
Odd. Works fine for me:

```
> rm .\bin\neko\Test.n
> haxe .\test_neko.hxml
> neko .\bin\neko\Test.n
Class: test.TestStructures .................
Class: test.Test2D ..............
Class: test.Test3D ...............
Class: test.TestMathUtil ..
Class: test.TestConverters ..
Class: test.TestFrames .......
Class: test.TestIntMath .
Class: test.TestGeom ..........
Class: test.TestDataStructures ...........
OK 79 tests, 0 failed, 79 success
```

Is the Test.n showing up somewhere else in your source dir?

**Comment by tbrosman** [comment]
Oh, is it possible you don't have nanotest installed? Run `haxelib install nanotest` though I don't know why the other builds would pass if this were the case.

**Comment by mboussaa** [comment]
I have already installed nanotest. all target platforms works fine except neko it is weird. I should maybe re-install neko 
`root@0b9babda64ab:/shared/hxmath# haxe ./test_neko.hxml
Uncaught exception - load.c(398) : Invalid module : target/neko/test.n
Error: Command failed with error 1
root@0b9babda64ab:/shared/hxmath# neko target/neko/test.n
Uncaught exception - load.c(398) : Invalid module : target/neko/test.`

**Comment by mboussaa** [comment]
another issue btw. Java code has one failed issue among the provided 79 test.

**Comment by tbrosman** [comment]
Good to know (I haven't tried Java yet for this library). What's the error?

**Comment by mboussaa** [comment]
![neki](https://cloud.githubusercontent.com/assets/5878565/14945849/87281bce-1019-11e6-9390-4b2c2796bdf3.png)

**Comment by mboussaa** [comment]
and python target generate the following error when run python test.py 

`  File "test.py", line 4496
    def print(self,v):
            ^
SyntaxError: invalid syntax
`

**Comment by tbrosman** [comment]
I'm not surprised that python is failing; it is an extremely new Haxe target. As for the Java target I'll look into that at some point. Kind of odd that particular test failed and no others.
