### ISSUE TITLE
Move XType typedefs into singular file

### ISSUE THREAD

**Issue by Yanrishatum** [tbrosman/hxmath#65]
I would like to suggest moving all typedefs that describe underlying types into a singular file. Reason for that is to ease up integration with different libraries that are not tied to OFL (and Heaps, since it's being added). If those typedefs are in one file, all it takes to redefine them is to make exact file in source project and utilize module override feature of Haxe. Akin to that:
```haxe
// src/hxmath/math/MathTypes.hx
package hxmath.math;

typedef IntVector2Type = my.lib.IVec2;
typedef Matrix2x2Type = my.lib.Mat2x2;
typedef Matrix3x2Type = my.lib.Mat3x3;
typedef Matrix3x3Type = my.lib.Mat3x3;
typedef Matrix4x4Type = my.lib.Mat4x4;
typedef QuaternionType = my.lib.Quat;
typedef Vector2Type = my.lib.Vec2;
typedef Vector3Type = my.lib.Vec3;
typedef Vector4Type = my.lib.Vec4;
```
That would make integration to other frameworks far easier on both sides. I can implement and PR it myself, but I want to get approval first. :)
That also would make implementing out-of-the-box framework support easier, as it would be all in one place instead of being spread over many files.
Another note is that I don't see much point in secondary `#if` in abstract constructors, as that should be covered by Type typedef (or in case of special constructors with different signature - abstracts: https://try.haxe.org/#470a5).

UPD: Sorry, pressed Ctrl+Enter instead of Ctrl+Backspace and posted not completely written issue early. Hand tremors.

**Comment by tbrosman** [comment]
I've actually been thinking about moving all the external type glue into a single file ever since @AustinEast started adding Heaps support. I didn't think of using a second abstract to translate constructors. That is pretty cool. Yes, I think this is a great change :) I would love a PR for this (though I might be slow to review, apologies in advance).
