### ISSUE TITLE
Using framework structures is a more sensible default

### ISSUE THREAD

**Issue by kevinresol** [tbrosman/hxmath#67]
... with an opt-out mechanism:

e.g.
```haxe
#if (openfl && !HXMATH_USE_DEFAULT_STRUCTURES)
// OpenFL types...
#elseif (heaps && !HXMATH_USE_DEFAULT_STRUCTURES)
// Heaps types...
#else
// Default types...
#end
````

If it is ok I can make a PR.

**Comment by tbrosman** [comment]
Interesting. I'm not sure I'd want to make it the default. Most libraries I've used don't change their datatypes automagically based on the presence of other libraries. That said, I like the idea of getting rid of some pre-processor gunk. I think something like this might make sense:

```
#if (openfl && HXMATH_USE_EXTERNAL_STRUCTURES)
// OpenFL types...
#elseif (heaps && HXMATH_USE_EXTERNAL_STRUCTURES)
// Heaps types...
#else
// Default types...
#end
```

The rationale here is "correctness first." From the perspective of an hxmath consumer, the safest choice is always going to be using the default structures. The implementation and semantics are all in the same place and tested together. As a library, hxmath can't make a guarantee that external libraries won't change their semantics/introduce a bug at some future version. It's unlikely, but possible.
