### ISSUE TITLE
Move `Test.hx` out of global namespace

### ISSUE THREAD

**Issue by AustinEast** [tbrosman/hxmath#76]
Hi! When attempting to make `hxmath` available for use on [try.haxe.org](https://try.haxe.org), I received [this comment](https://github.com/HaxeFoundation/try.haxe.org/pull/1#issuecomment-787127985) from the maintainer. It mentions that because the `Test` class is in the root of the project, it gets included in the global namespace for any project that is using `hxmath` through haxelib. I checked it out in my own projects, and it is indeed happening, which isn't really desirable.

Easiest solution would probably be to move the file into `test/`, but I wanted to get input before making a PR.

**Comment by tbrosman** [comment]
Sounds like a good idea! You might have to tweak the travis.yml file though.

**Comment by AlexHaxe** [comment]
maybe even consider moving `hxmath` folder into a `src` subfolder and adding `"classPath": "src",` to `haxelib.json`.

because with current folder structure even if `Test.hx` is moved into `test` someone could still end up having types from `test` package show up in their unittests / project.
