### ISSUE TITLE
hxmath added to try.haxe.org!

### ISSUE THREAD

**Issue by AustinEast** [tbrosman/hxmath#78]
this is not a real issue, but i just wanted to notify you that hxmath has been added to the new try.haxe website! demo is here:

https://try.haxe.org/#17Fd1680

feel free to close this as soon as you see it 😁

**Comment by tbrosman** [comment]
I like it! I saw the HackerNews post last week but hadn't had a chance to check it out. I like that you can just include libraries with checkboxes.
